In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import warnings  
warnings.filterwarnings("ignore")   # ignore warnings

In [10]:
data = pd.read_csv('D:\\DATA SCIENCE\\NLP\\employee_reviews.csv',encoding='latin1')
data.head()

Unnamed: 0 company           location          dates  \
0           1  google               none   Dec 11, 2018   
1           2  google  Mountain View, CA   Jun 21, 2013   
2           3  google       New York, NY   May 10, 2014   
3           4  google  Mountain View, CA    Feb 8, 2015   
4           5  google    Los Angeles, CA   Jul 19, 2018   

                                  job-title  \
0     Current Employee - Anonymous Employee   
1         Former Employee - Program Manager   
2  Current Employee - Software Engineer III   
3     Current Employee - Anonymous Employee   
4       Former Employee - Software Engineer   

                                             summary  \
0                           Best Company to work for   
1  Moving at the speed of light, burn out is inev...   
2  Great balance between big-company security and...   
3  The best place I've worked and also the most d...   
4                    Unique, one of a kind dream job   

                                                pros  \
0                      People are smart and friendly   
1  1) Food, food, food. 15+ cafes on main campus ...   
2  * If you're a software engineer, you're among ...   
3  You can't find a more well-regarded company th...   
4  Google is a world of its own. At every other c...   

                                                cons  \
0                 Bureaucracy is slowing things down   
1  1) Work/life balance. What balance? All those ...   
2  * It *is* becoming larger, and with it comes g...   
3  I live in SF so the commute can take between 1...   
4  If you don't work in MTV (HQ), you will be giv...   

                                      advice-to-mgmt  overall-ratings  \
0                                               none                5   
1  1) Don't dismiss emotional intelligence and ad...                4   
2  Keep the focus on the user. Everything else wi...                5   
3  Keep on NOT micromanaging - that is a huge ben...                5   
4  Promote managers into management for their man...                5   

  work-balance-stars culture-values-stars carrer-opportunities-stars  \
0                  4                    5                          5   
1                  2                    3                          3   
2                  5                    4                          5   
3                  2                    5                          5   
4                  5                    5                          5   

  comp-benefit-stars senior-mangemnet-stars  helpful-count  \
0                  4                      5              0   
1                  5                      3           2094   
2                  5                      4            949   
3                  4                      5            498   
4                  5                      5             49   

                                                link  
0  https://www.glassdoor.com/Reviews/Google-Revie...  
1  https://www.glassdoor.com/Reviews/Google-Revie...  
2  https://www.glassdoor.com/Reviews/Google-Revie...  
3  https://www.glassdoor.com/Reviews/Google-Revie...  
4  https://www.glassdoor.com/Reviews/Google-Revie...

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67529 entries, 0 to 67528
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Unnamed: 0                  67529 non-null  int64 
 1   company                     67529 non-null  object
 2   location                    67529 non-null  object
 3   dates                       67529 non-null  object
 4   job-title                   67529 non-null  object
 5   summary                     67409 non-null  object
 6   pros                        67529 non-null  object
 7   cons                        67529 non-null  object
 8   advice-to-mgmt              67232 non-null  object
 9   overall-ratings             67529 non-null  int64 
 10  work-balance-stars          67529 non-null  object
 11  culture-values-stars        67529 non-null  object
 12  carrer-opportunities-stars  67529 non-null  object
 13  comp-benefit-stars          67529 non-null  ob

In [12]:
data.iloc[:,9:10]

overall-ratings
0                    5
1                    4
2                    5
3                    5
4                    5
...                ...
67524                3
67525                3
67526                4
67527                3
67528                2

[67529 rows x 1 columns]

In [13]:
data["overall_ratings"]=data["overall-ratings"]

In [14]:
data['overall_ratings'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [15]:
# Comprehension list

data["Liked"] = [1 if i >=3 else 0 for i in data.overall_ratings]
data.tail()

Unnamed: 0    company location          dates  \
67524       67525  microsoft     none   Dec 16, 2010   
67525       67526  microsoft     none   Dec 16, 2010   
67526       67527  microsoft     none   Dec 15, 2010   
67527       67528  microsoft     none   Dec 15, 2010   
67528       67529  microsoft     none   Dec 14, 2010   

                                         job-title  \
67524         Former Employee - Anonymous Employee   
67525  Current Employee - Senior Marketing Manager   
67526           Current Employee - Account Manager   
67527          Current Employee - Senior Test Lead   
67528            Former Employee - Senior Director   

                                                 summary  \
67524  Enriching experience for a beginner but bad fo...   
67525               A complex and interesting experience   
67526                                 Good Place to Work   
67527  It's a competitive work place, with overload w...   
67528                                   Used to be great   

                                                    pros  \
67524  -Access to a wide range of technologies, compl...   
67525  - Once you're at Microsoft you can change role...   
67526  Nice place to work. Good atmosphere with advan...   
67527       Smart people around you, can learn from them   
67528  Compensation, Health benefits and brand name r...   

                                                    cons  \
67524  -Testers(SDET's ) do not get as many opportuni...   
67525  =- be prepared to be Flexible - Frequent chang...   
67526  Management confusion at times with vision for ...   
67527              Politics, weak moral, leaning loyalty   
67528  Leadership was better in the late 90's....its ...   

                                          advice-to-mgmt  overall-ratings  \
67524  Make the company leaner and Meaner. (which wou...                3   
67525                                               none                3   
67526                                               none                4   
67527                                               none                3   
67528  Good people keep leaving...you have to ask you...                2   

      work-balance-stars culture-values-stars carrer-opportunities-stars  \
67524                  3                 none                          4   
67525                1.5                 none                        2.5   
67526                  3                 none                          4   
67527                  2                 none                          3   
67528                  2                 none                          2   

      comp-benefit-stars senior-mangemnet-stars  helpful-count  \
67524                  4                      2              0   
67525                  4                    2.5              0   
67526                4.5                    3.5              0   
67527                3.5                      3              0   
67528                  4                      2              0   

                                                    link  overall_ratings  \
67524  https://www.glassdoor.com/Reviews/Microsoft-Re...                3   
67525  https://www.glassdoor.com/Reviews/Microsoft-Re...                3   
67526  https://www.glassdoor.com/Reviews/Microsoft-Re...                4   
67527  https://www.glassdoor.com/Reviews/Microsoft-Re...                3   
67528  https://www.glassdoor.com/Reviews/Microsoft-Re...                2   

       Liked  
67524      1  
67525      1  
67526      1  
67527      1  
67528      0

In [16]:
part1 = data.iloc[:,-1:]
part1

Liked
0          1
1          1
2          1
3          1
4          1
...      ...
67524      1
67525      1
67526      1
67527      1
67528      0

[67529 rows x 1 columns]

In [17]:
part2 = data.iloc[:,6:7]
part2

pros
0                          People are smart and friendly
1      1) Food, food, food. 15+ cafes on main campus ...
2      * If you're a software engineer, you're among ...
3      You can't find a more well-regarded company th...
4      Google is a world of its own. At every other c...
...                                                  ...
67524  -Access to a wide range of technologies, compl...
67525  - Once you're at Microsoft you can change role...
67526  Nice place to work. Good atmosphere with advan...
67527       Smart people around you, can learn from them
67528  Compensation, Health benefits and brand name r...

[67529 rows x 1 columns]

In [18]:
comment = pd.concat([part2,part1],axis =1,ignore_index =True) 
comment

0  1
0                          People are smart and friendly  1
1      1) Food, food, food. 15+ cafes on main campus ...  1
2      * If you're a software engineer, you're among ...  1
3      You can't find a more well-regarded company th...  1
4      Google is a world of its own. At every other c...  1
...                                                  ... ..
67524  -Access to a wide range of technologies, compl...  1
67525  - Once you're at Microsoft you can change role...  1
67526  Nice place to work. Good atmosphere with advan...  1
67527       Smart people around you, can learn from them  1
67528  Compensation, Health benefits and brand name r...  0

[67529 rows x 2 columns]

In [19]:
comment.columns = ['Review', 'Liked']
comment

Review  Liked
0                          People are smart and friendly      1
1      1) Food, food, food. 15+ cafes on main campus ...      1
2      * If you're a software engineer, you're among ...      1
3      You can't find a more well-regarded company th...      1
4      Google is a world of its own. At every other c...      1
...                                                  ...    ...
67524  -Access to a wide range of technologies, compl...      1
67525  - Once you're at Microsoft you can change role...      1
67526  Nice place to work. Good atmosphere with advan...      1
67527       Smart people around you, can learn from them      1
67528  Compensation, Health benefits and brand name r...      0

[67529 rows x 2 columns]

# Regular Expression

Removing alphanumeric, spelling and punctuation characters

In [20]:
import re
com = re.sub('[^a-zA-Z]', ' ', comment['Review'][1])
com

'   Food  food  food      cafes on main campus  MTV  alone  Mini kitchens  snacks  drinks  free breakfast lunch dinner  all day  errr day      Benefits perks  Free      gym access  on MTV campus   Free  self service  laundry  washer dryer  available  Bowling alley  Volley ball pit  Custom built and exclusive employee use only outdoor sport park  MTV   Free health fitness assessments  Dog friendly  Etc  etc  etc      Compensation  In       or       Google updated its compensation packages so that they were more competitive      For the size of the organization    K    it has remained relatively innovative  nimble  and fast paced and open with communication but  that is definitely changing  for the worse       With so many departments  focus areas  and products   in theory   you should have plenty of opportunity to grow your career  horizontally or vertically   In practice  not true      You get to work with some of the brightest  most innovative and hard working diligent minds in the in

After data preprocessing, comment data set is obtained from data that is loaded from csv file.

Hereafter, comment will be used in this kernel as data set.

In [21]:
# Conversion all letters to lower case 
com = com.lower()
com

'   food  food  food      cafes on main campus  mtv  alone  mini kitchens  snacks  drinks  free breakfast lunch dinner  all day  errr day      benefits perks  free      gym access  on mtv campus   free  self service  laundry  washer dryer  available  bowling alley  volley ball pit  custom built and exclusive employee use only outdoor sport park  mtv   free health fitness assessments  dog friendly  etc  etc  etc      compensation  in       or       google updated its compensation packages so that they were more competitive      for the size of the organization    k    it has remained relatively innovative  nimble  and fast paced and open with communication but  that is definitely changing  for the worse       with so many departments  focus areas  and products   in theory   you should have plenty of opportunity to grow your career  horizontally or vertically   in practice  not true      you get to work with some of the brightest  most innovative and hard working diligent minds in the in

In [22]:
# Splitting word by word 
com = com.split()
com

['food',
 'food',
 'food',
 'cafes',
 'on',
 'main',
 'campus',
 'mtv',
 'alone',
 'mini',
 'kitchens',
 'snacks',
 'drinks',
 'free',
 'breakfast',
 'lunch',
 'dinner',
 'all',
 'day',
 'errr',
 'day',
 'benefits',
 'perks',
 'free',
 'gym',
 'access',
 'on',
 'mtv',
 'campus',
 'free',
 'self',
 'service',
 'laundry',
 'washer',
 'dryer',
 'available',
 'bowling',
 'alley',
 'volley',
 'ball',
 'pit',
 'custom',
 'built',
 'and',
 'exclusive',
 'employee',
 'use',
 'only',
 'outdoor',
 'sport',
 'park',
 'mtv',
 'free',
 'health',
 'fitness',
 'assessments',
 'dog',
 'friendly',
 'etc',
 'etc',
 'etc',
 'compensation',
 'in',
 'or',
 'google',
 'updated',
 'its',
 'compensation',
 'packages',
 'so',
 'that',
 'they',
 'were',
 'more',
 'competitive',
 'for',
 'the',
 'size',
 'of',
 'the',
 'organization',
 'k',
 'it',
 'has',
 'remained',
 'relatively',
 'innovative',
 'nimble',
 'and',
 'fast',
 'paced',
 'and',
 'open',
 'with',
 'communication',
 'but',
 'that',
 'is',
 'definite

# Cleaning the stop words

In [23]:
# Loading stopwords

import nltk
from nltk.corpus import stopwords
stopwords_en = stopwords.words('english')
print(stopwords_en)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [24]:
# Cleaning the stop words
# In here, we use set function because set is unordered and same element within set passes only one time.
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

com = [ps.stem(word) for word in com if not word in set(stopwords.words('english'))]
com

['food',
 'food',
 'food',
 'cafe',
 'main',
 'campu',
 'mtv',
 'alon',
 'mini',
 'kitchen',
 'snack',
 'drink',
 'free',
 'breakfast',
 'lunch',
 'dinner',
 'day',
 'errr',
 'day',
 'benefit',
 'perk',
 'free',
 'gym',
 'access',
 'mtv',
 'campu',
 'free',
 'self',
 'servic',
 'laundri',
 'washer',
 'dryer',
 'avail',
 'bowl',
 'alley',
 'volley',
 'ball',
 'pit',
 'custom',
 'built',
 'exclus',
 'employe',
 'use',
 'outdoor',
 'sport',
 'park',
 'mtv',
 'free',
 'health',
 'fit',
 'assess',
 'dog',
 'friendli',
 'etc',
 'etc',
 'etc',
 'compens',
 'googl',
 'updat',
 'compens',
 'packag',
 'competit',
 'size',
 'organ',
 'k',
 'remain',
 'rel',
 'innov',
 'nimbl',
 'fast',
 'pace',
 'open',
 'commun',
 'definit',
 'chang',
 'wors',
 'mani',
 'depart',
 'focu',
 'area',
 'product',
 'theori',
 'plenti',
 'opportun',
 'grow',
 'career',
 'horizont',
 'vertic',
 'practic',
 'true',
 'get',
 'work',
 'brightest',
 'innov',
 'hard',
 'work',
 'dilig',
 'mind',
 'industri',
 'con',
 'see']

Combining process

In [25]:
com = ' '.join(com)
com

'food food food cafe main campu mtv alon mini kitchen snack drink free breakfast lunch dinner day errr day benefit perk free gym access mtv campu free self servic laundri washer dryer avail bowl alley volley ball pit custom built exclus employe use outdoor sport park mtv free health fit assess dog friendli etc etc etc compens googl updat compens packag competit size organ k remain rel innov nimbl fast pace open commun definit chang wors mani depart focu area product theori plenti opportun grow career horizont vertic practic true get work brightest innov hard work dilig mind industri con see'

Making loop

In [27]:
result = []
for i in range(67529):
    com = re.sub('[^a-zA-Z]', ' ', comment['Review'][i])
    com = com.lower()
    com = com.split()
    com = [ps.stem(word) for word in com if not word in set(stopwords.words('english'))]
    com = ' '.join(com)
    result.append(com)

In [28]:
result

['peopl smart friendli',
 'food food food cafe main campu mtv alon mini kitchen snack drink free breakfast lunch dinner day errr day benefit perk free gym access mtv campu free self servic laundri washer dryer avail bowl alley volley ball pit custom built exclus employe use outdoor sport park mtv free health fit assess dog friendli etc etc etc compens googl updat compens packag competit size organ k remain rel innov nimbl fast pace open commun definit chang wors mani depart focu area product theori plenti opportun grow career horizont vertic practic true get work brightest innov hard work dilig mind industri con see',
 'softwar engin among king hill googl engin driven compani without doubt chang still engin focus perk amaz ye free breakfast lunch dinner everi weekday aaaaaamaz holiday parti waldorf astoria ny public librari moma etc overnight ski trip vermont overnight natur trip pocono summer summer picnic chelsea pier see go away unless compani start hurt financi speak compani quit w

In [29]:
# Feature Extraction (Bag of Words (BOW))
from sklearn.feature_extraction.text import CountVectorizer

### We take most used 2000 words 
cv = CountVectorizer(max_features=2000)

X = cv.fit_transform(result).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
y = comment.iloc[:,1].values
y

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [31]:
# Machine Learning Part
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [32]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[1583,  244],
       [8884, 2795]], dtype=int64)